# Generated by Django 5.2.5 on 2025-08-28 20:27

import pos_server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_serial', models.CharField(default=pos_server.models.generate_serial, max_length=255, unique=True)),
                ('initialization_token', models.CharField(default=pos_server.models.generate_initialization_token, max_length=255, unique=True)),
                ('api_token', models.CharField(max_length=255, null=True, unique=True)),
                ('revoked', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('initialized', models.DateTimeField(blank=True, null=True, verbose_name='Initialized at')),
            ],
        ),
    ]
