# Generated by Django 5.2.5 on 2025-08-28 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_token',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='API Token'),
        ),
        migrations.CreateModel(
            name='WebsocketToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_server.device')),
            ],
        ),
    ]
