# Generated by Django 5.2.5 on 2025-08-22 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coap_server', '0001_initial'),
        ('vas', '0004_alter_applepass_pass_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='config_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='vas.configgroup'),
        ),
    ]
