# Generated by Django 5.2.5 on 2025-08-22 15:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSmartTapCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('collector_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)])),
                ('key_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)])),
                ('private_key', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Google Smart Tap Collector',
            },
        ),
        migrations.CreateModel(
            name='GoogleSmartTapConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('store_location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('merchant_name', models.CharField(max_length=255)),
                ('merchant_category', models.PositiveIntegerField(help_text='4-digit MCC', validators=[django.core.validators.MaxValueValidator(9999)])),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vas.googlesmarttapcollector')),
            ],
            options={
                'verbose_name': 'Google Smart Tap Configuration',
            },
        ),
        migrations.CreateModel(
            name='ConfigGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('google_smart_tap_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vas.googlesmarttapconfiguration')),
            ],
            options={
                'verbose_name': 'Config Group',
            },
        ),
        migrations.CreateModel(
            name='GoogleSmartTapService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.PositiveSmallIntegerField(choices=[(0, 'All services'), (1, 'All services except PPSE'), (2, 'PPSE'), (3, 'Loyalty'), (4, 'Offer'), (5, 'Gift card'), (6, 'Private label card'), (7, 'Event ticket'), (8, 'Flight'), (9, 'Transit'), (16, 'Cloud-based wallet'), (17, 'Mobile marketing platform'), (18, 'Generic'), (19, 'Generic Private Pass'), (64, 'Wallet customer')])),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vas.googlesmarttapconfiguration')),
            ],
        ),
    ]
