# Generated by Django 5.2.5 on 2025-08-22 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesmarttapcollector',
            name='collector_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)], verbose_name='Collector ID'),
        ),
        migrations.AlterField(
            model_name='googlesmarttapconfiguration',
            name='merchant_category',
            field=models.PositiveIntegerField(blank=True, help_text='4-digit MCC', null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='googlesmarttapconfiguration',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
