# Generated by Django 5.2.5 on 2025-08-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vas', '0002_alter_googlesmarttapcollector_collector_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Apple PKPass',
                'verbose_name_plural': 'Apple PKPasses',
            },
        ),
        migrations.CreateModel(
            name='ApplePassKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.BinaryField()),
                ('private_key', models.BinaryField()),
                ('apple_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vas.applepass')),
            ],
        ),
        migrations.CreateModel(
            name='AppleVASConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passes', models.ManyToManyField(blank=True, to='vas.applepass')),
            ],
            options={
                'verbose_name': 'Apple VAS Configuration',
            },
        ),
        migrations.AddField(
            model_name='configgroup',
            name='apple_vas_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vas.applevasconfiguration'),
        ),
    ]
