# Generated by Django 5.2.5 on 2025-08-22 16:18

import django.db.models.deletion
import vas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vas', '0003_applepass_applepasskey_applevasconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applepass',
            name='pass_id',
            field=models.CharField(max_length=255, unique=True, validators=[vas.models.validate_apple_pass_id], verbose_name='Apple Pass ID'),
        ),
        migrations.AlterField(
            model_name='configgroup',
            name='apple_vas_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_groups', to='vas.applevasconfiguration', verbose_name='Apple VAS configuration'),
        ),
        migrations.AlterField(
            model_name='configgroup',
            name='google_smart_tap_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_groups', to='vas.googlesmarttapconfiguration', verbose_name='Google Smart Tap configuration'),
        ),
        migrations.AlterField(
            model_name='googlesmarttapconfiguration',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configs', to='vas.googlesmarttapcollector'),
        ),
        migrations.AlterField(
            model_name='googlesmarttapservice',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vas.googlesmarttapconfiguration'),
        ),
    ]
