# Generated by Django 5.2.5 on 2025-08-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vas', '0004_alter_applepass_pass_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applepasskey',
            name='apple_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='vas.applepass'),
        ),
    ]
